#! /bin/bash

verLevel=0

if [ ! -d "$openarc" ]; then
	echo "Environment variable, openarc should be set to the root directory of the OpenARC repository; exit!\n"
fi

openarcrt="$openarc/openarcrt"
openarclib="$openarc/lib"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt kernels.c
