#! /bin/bash
if [ $# -ge 3 ]; then
    runMode=$1
	aspen_param=$2
	postprocessing=$3
elif [ $# -ge 2 ]; then
    runMode=$1
	aspen_param=$2
	postprocessing=2
elif [ $# -ge 1 ]; then
    runMode=$1
	aspen_param=512
	postprocessing=2
else
    runMode=3
	aspen_param=512
	postprocessing=2
fi

if [ "$runMode" = "4" ]; then
    aspenrt="./cetus_output/aspenrt.c"
else
    aspenrt=""
fi

openarcrt="../../../../openarcrt"
openarclib="../../../../lib"

benchname="matmul"
verLevel=0

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$aspen_param" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__aspen_param__|${aspen_param}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt -ASPENModelGen=mode=${runMode}:modelname=${benchname}:postprocessing=${postprocessing} *.c ${aspenrt}
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; matmul_ACC"
echo ""
